### ISSUE TITLE
PNNL shares video tutorials for the way ADBio is supposed to work

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-pnnl#10]
The newest ones are being uploaded to youtube.  This is the previous version, which is still accurate, but lacks the new look and feel:

https://www.youtube.com/watch?list=PLdW5J6qhxuwCJIJSUcxRroYEbpOQKEeL3&v=lM12rP0Gl9Y

**Comment by Tweety79rw** [comment]
I must have missed this issue here are the new videos
Overview: https://www.youtube.com/watch?v=RhxOYWDTzhA&t=10s
Heat map: https://www.youtube.com/watch?v=EtSj7HxRE84&t=11s
Pathway: https://www.youtube.com/watch?v=LU280SWWFUc&t=1s

**Comment by Tweety79rw** [comment]
@danfowler I think this issue can be closed we don't have any other videos yet.

**Comment by danfowler** [comment]
Great, thanks @Tweety79rw
