### ISSUE TITLE
Create program to automatically create schema for metadata.tsv

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-pnnl#15]
Originally proposed: 

> @danfowler @coldfire79 @samuelpayne Hi Dan, I am planning to make a program to generates a basic schema for metadata.tsv based off what you have made for adb_user_study's. This way someone that creates a project for adbio doesn't have to provide their own. Is there any specifics about the scheme that I should know to make it integrate with good tables. Or if there is anything you need me to help with let me know.

**Comment by pwalsh** [comment]
@danfowler is this still relevant? Can the issue be closed?

**Comment by danfowler** [comment]
I am interested in how @Tweety79rw created [this schema](https://github.com/PNNL-Comp-Mass-Spec/MetabolomicsCCS/blob/master/metabolitedata-schema.json) but for the purposes of the pilot, we can close.

**Comment by Tweety79rw** [comment]
@danfowler  The schema was mostly copy and paste from the adbio demo schema then modify to work with [this data set](https://github.com/PNNL-Comp-Mass-Spec/MetabolomicsCCS/blob/master/data/metabolitedata.tsv).
