### ISSUE TITLE
Demo current status

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-pnnl#17]
@Tweety79rw @samuelpayne @coldfire79 

https://github.com/frictionlessdata/ADB-User-Study is a fork of https://github.com/ActiveDataBio/ADB-User-Study.

Three files were added: (1) [goodtables.yml](https://github.com/frictionlessdata/ADB-User-Study/blob/master/goodtables.yml), (2) [metadata-schema.json](https://github.com/frictionlessdata/ADB-User-Study/blob/master/metadata-schema.json), and (3) [datapackage.json](https://github.com/frictionlessdata/ADB-User-Study/blob/master/datapackage.json) (currently ignored).  goodtables.yml [defines the job](https://github.com/frictionlessdata/goodtables.io/blob/48ed5ff9b7aab287c617d0acf99c30b07f66808c/goodtablesio/schemas/job-conf.yml) for the goodtables.io service.  It points to `metadata-schema.json` as the [Table Schema](http://specs.frictionlessdata.io/json-table-schema/) for `metadata.tsv`.

On every commit, the file structure is checked as well as its adherence to the Table Schema.  

Here is an example valid job report:

[![screen shot 2017-01-26 at 17 03 31](https://cloud.githubusercontent.com/assets/772616/22352308/8a9609de-e3e9-11e6-8b0f-222b9a348a86.png)](http://goodtables.oklabs.org/jobs/3d9d13cd-eecf-48b3-b5f6-ba8c3562bf72)

And here is an example invalid job report:

[![screen shot 2017-01-26 at 17 03 20](https://cloud.githubusercontent.com/assets/772616/22352326/98164a88-e3e9-11e6-88ae-4296f466585c.png)](http://goodtables.oklabs.org/jobs/21ff2708-4c66-47af-8406-fcb8ab3a6aa1)

It is invalid because rows 2 & 3 contain metadata, and not data.  This is why we had to add `skip_rows` key to `goodtables.yml`.  I'd be curious to hear your thoughts here.

Let me know what you think!

**Comment by Tweety79rw** [comment]
@danfowler 
You say on every commit, so when I commit metadata.tsv file the good table service runs and would display a report?  Would committing through the github api return a json object that could then be used to show the committer where the errors are? Does the commit succeed?

I like the ability to ignore rows if there isn't a proper format that needs to be adhered to.

**Comment by amercader** [comment]
@Tweety79rw we are using a GitHub [webhook](https://developer.github.com/webhooks/#events) for triggering validation jobs on goodtables.io. Once a validation job is finished the status on GitHub is updated and you can see the success or failure marks with a link to the report, which includes the location of the errors:

![001ee8c4-b7e4-11e6-9e8b-b88390a659c7](https://cloud.githubusercontent.com/assets/200230/22936333/182f501a-f2cd-11e6-997f-40a46fca68bc.png)

This is independent of the actual commit, which is not affected regardless of the validation output.

If I understood the documentation correctly, commiting via the GitHub API will also trigger a validation job.

**Comment by Tweety79rw** [comment]
@amercader Thanks that explains a lot.

**Comment by amercader** [comment]
@Tweety79rw We are currently redeploying the staging goodtables.io site to a new platform. When that is finished I'll trigger some jobs and post some actual links so you get a better idea of how it works

**Comment by danfowler** [comment]
@Tweety79rw @samuelpayne @coldfire79 will send a more substantive email soon, but have a look at http://goodtables.io/

For example: http://goodtables.io/github/frictionlessdata/ADB-User-Study
