### ISSUE TITLE
Create Table Schema for metadata.tsv

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-pnnl#5]
metadata.tsv: https://github.com/ActiveDataBio/Prochlorococcus/blob/master/metadata.tsv
Table Schema: http://specs.frictionlessdata.io/json-table-schema/

@Tweety79rw are you interested in doing this?  Either manually or partially automated?

**Comment by danfowler** [comment]
@Tweety79rw now with the goodtables.io, this would be a good time to try this out

**Comment by pwalsh** [comment]
@danfowler is this still relevant? Can the issue be closed?

**Comment by danfowler** [comment]
@pwalsh @Tweety79rw Given that the equivalent work (creating of a Table Schema, addition of goodtables.io config, and continuous validation) is happening to good effect in a new repo (https://github.com/PNNL-Comp-Mass-Spec/MetabolomicsCCS), we can close this.
